# Configuration de la base de données (Mital b MySQL)
spring.datasource.url=jdbc:mysql://localhost:3307/kyntusdotma_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Le port de l'application (Optionnel, bach mayt-conflictach m3a Next.js li kaykhdem f 3000)
server.port=8081
# Spring Datasource & JPA configuration (khli dakchi li knti dayr 9bel w zid hado lta7t)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Custom property dyalna fin ghadi yetkhb3o les CVs
file.upload-dir=uploads/cvs/